In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
limit = 10
x = t = y = 1
fList = []
while y < limit:
    fList.append(y)
    y = x + t
    x = t
    t = y
fList

[1, 2, 3, 5, 8]

In [5]:
def isPrime(number):
    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            return False
    else:
        return True
    
n = 600851475143
while not isPrime(n):
    for i in range(2, n):
        if n % i == 0:
            n = int(n / i)
            break
else:
    print(n)

6857


In [11]:
arr1, arr2 = np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]])
np.concatenate((arr1, arr2), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [6]:
print(np.array([[1, 2], [3, 4]]) * np.array([[1, 2], [3, 4]]))
print(np.matmul(np.array([[1, 2], [3, 4]]), np.array([[1, 2], [3, 4]])))

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [15]:
data = {'calories': [420, 380, 390], 'duration': [50, 40, -45]}
df = pd.DataFrame(data, index = ['day2', 'day3', 'day1'])
df

calories  duration
day2       420        50
day3       380        40
day1       390       -45

In [16]:
df[df < 0] = -df
df

calories  duration
day2       420        50
day3       380        40
day1       390        45

In [17]:
list(df['calories'])

[420, 380, 390]

In [18]:
df.iloc[0, 0] = '420'
df

calories  duration
day2      420        50
day3      380        40
day1      390        45

In [19]:
list(df['calories'])

['420', 380, 390]

In [107]:
x = np.array([80, 85, 90, 95, 100, 105, 110, 115, 120, 125])
y = np.array([240, 255, 259, 265, 270, 290, 305, 306, 325, 330])
titleFont = {'family': 'Trebuchet MS','color': '#0091EA','size': 14}
labelFont = {'family': 'Consolas', 'color': 'black', 'size': 11}
plt.plot(x, y)
plt.title('Sports Watch Data', titleFont)
plt.xlabel('Average Pulse', labelFont)
plt.ylabel('Calorie Burnage', labelFont)
plt.grid()
plt.show()


In [3]:
df = pd.read_excel('./Files/superstore.xlsx')
df

d:\Users\a.nezhadshamsi\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")


Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2018-152156 2018-11-08 2018-11-11    Second Class   
1          2  CA-2018-152156 2018-11-08 2018-11-11    Second Class   
2          3  CA-2018-138688 2018-06-12 2018-06-16    Second Class   
3          4  US-2017-108966 2017-10-11 2017-10-18  Standard Class   
4          5  US-2017-108966 2017-10-11 2017-10-18  Standard Class   
...      ...             ...        ...        ...             ...   
9989    9990  CA-2016-110422 2016-01-21 2016-01-23    Second Class   
9990    9991  CA-2019-121258 2019-02-26 2019-03-03  Standard Class   
9991    9992  CA-2019-121258 2019-02-26 2019-03-03  Standard Class   
9992    9993  CA-2019-121258 2019-02-26 2019-03-03  Standard Class   
9993    9994  CA-2019-119914 2019-05-04 2019-05-09    Second Class   

     Customer ID     Customer Name    Segment Country/Region             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson   
1       CG-12520       Claire Gute   Consumer  United States        Henderson   
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles   
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale   
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale   
...          ...               ...        ...            ...              ...   
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami   
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster   

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...     42420.0   South  FUR-BO-10001798        Furniture    Bookcases   
1     ...     42420.0   South  FUR-CH-10000454        Furniture       Chairs   
2     ...     90036.0    West  OFF-LA-10000240  Office Supplies       Labels   
3     ...     33311.0   South  FUR-TA-10000577        Furniture       Tables   
4     ...     33311.0   South  OFF-ST-10000760  Office Supplies      Storage   
...   ...         ...     ...              ...              ...          ...   
9989  ...     33180.0   South  FUR-FU-10001889        Furniture  Furnishings   
9990  ...     92627.0    West  FUR-FU-10000747        Furniture  Furnishings   
9991  ...     92627.0    West  TEC-PH-10003645       Technology       Phones   
9992  ...     92627.0    West  OFF-PA-10004041  Office Supplies        Paper   
9993  ...     92683.0    West  OFF-AP-10002684  Office Supplies   Appliances   

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2   
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                        Eldon Fold 'N Roll Cart System   22.3680         2   
...                                                 ...       ...       ...   
9989                             Ultra Door Pull Handle   25.2480         3   
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2   
9991                              Aastra 57i VoIP phone  258.5760         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
2         0.00    6.8714  
3         0.45 -383.0310  
4         0.20    2.5164  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20   19.3932  
9992      0.

In [4]:
df.plot(kind = 'scatter', x = 'Sales', y = 'Profit')

<AxesSubplot: xlabel='Sales', ylabel='Profit'>

In [8]:
df['Discount'].plot(kind = 'hist')

<AxesSubplot: ylabel='Frequency'>