In [ ]:
x = 18
if x >= 10 and x <= 20:
    print('Pass', end = ' ')
    if x >= 18:
        print('with grade A!')
    elif x >= 15:
        print('with grade B!')
    elif x >= 12:
        print('with grade C!')
    else:
        print('with grade D!')
elif x < 10 and x >= 0:
    print('Fail!')
else:
    print('Wrong input!')

In [ ]:
x = 18
if x >= 10 and x <= 20:
    print('Pass', end = ' ')
    print('with grade A!') if x >= 18 else print('with grade B!') if x >= 15 else print('with grade C!') if x >= 12 else print('with grade D!') 
elif x < 10 and x >= 0:
    print('Fail!')
else:
    print('Wrong input!')

In [ ]:
import numpy as np
arr = np.array(['a', 'b', 'c', 'd'])
print(arr.dtype) 

In [ ]:
myList = []
for x in range(1, 10):
    if x % 3 == 0 or x % 5 == 0:
        myList.append(x)
myList

In [ ]:
sum(myList)

In [ ]:
limit = 10
x = t = y = 1
fList = []

In [ ]:
while y < limit:
    fList.append(y)
    y = x + t
    x = t
    t = y

In [ ]:
fList

In [53]:
def isPrime(number):
    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            return False
    else:
        return True

In [64]:
n = 600851475143
while not isPrime(n):
    for i in range(2, n):
        if n % i == 0:
            n = int(n / i)
            break
else:
    print(n)

6857


In [34]:
import pandas as pd

In [3]:
data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}
df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])
df.loc['day2']

calories    380
duration     40
Name: day2, dtype: int64

In [10]:
print(df, df.head(), df.tail(), df.info())


<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, day1 to day3
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   calories  3 non-null      int64
 1   duration  3 non-null      int64
dtypes: int64(2)
memory usage: 180.0+ bytes
      calories  duration
day1       420        50
day2       380        40
day3       390        45       calories  duration
day1       420        50
day2       380        40
day3       390        45       calories  duration
day1       420        50
day2       380        40
day3       390        45 None


In [16]:
calories = {'day1': 420, 'day2': 380, 'day3': 390}
s = pd.Series(calories)
print(s['day2'])


380


In [26]:
data = {'calories': [420, 380, 390], 'duration': [50, 40, 45]}
df = pd.DataFrame(data)
df['calories']

0    420
1    380
2    390
Name: calories, dtype: int64

In [11]:
arr1, arr2 = np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]])
np.concatenate((arr1, arr2), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
np.array([[1, 2], [3, 4]]) * np.array([[1, 2], [3, 4]])

array([[ 1,  4],
       [ 9, 16]])

In [31]:
np.matmul(np.array([[1, 2], [3, 4]]), np.array([[1, 2], [3, 4]]))


array([[ 7, 10],
       [15, 22]])

In [35]:
data = {'calories': [420, 380, 390], 'duration': [50, 40, -45]}
df = pd.DataFrame(data, index = ['day2', 'day3', 'day1'])
df

calories  duration
day2       420        50
day3       380        40
day1       390       -45

In [37]:
print(df.sort_index())
print(df.sort_values(by = 'calories'))
df

      calories  duration
day1       390       -45
day2       420        50
day3       380        40
      calories  duration
day3       380        40
day1       390       -45
day2       420        50


calories  duration
day2       420        50
day3       380        40
day1       390       -45

In [42]:
df[df < 0] = -df

In [44]:
df

calories  duration
day2       420        50
day3       380        40
day1       390        45

In [46]:
df.iloc[0, 0] = '420'
df

calories  duration
day2      420        50
day3      380        40
day1      390        45

In [64]:
df['calories'].dtype

dtype('int32')

In [62]:
list(df['calories'])

[420, 380, 390]